#!/usr/bin/env bash

# Change route to results and the model list in Python files to save all ensemble results

echo "=========="
echo "=========="
echo "=========="
echo "===== Hard ====="
echo "=========="
echo "=========="
echo "=========="
python3 -u ensemble_voting.py --mode hard --debug --save-preds ../approaches/moral-values/output/moral-values-fixed-hard-champion-val.tsv | tee ensemble_results/presence/moral-values-fixed-hard.txt
echo "=========="
echo "=========="
echo "=========="
echo "===== Soft ====="
echo "=========="
echo "=========="
echo "=========="
python3 -u ensemble_voting.py --mode soft --debug --save-preds ../approaches/moral-values/output/moral-values-fixed-soft-champion-val.tsv | tee ensemble_results/presence/moral-values-fixed-soft.txt
echo "=========="
echo "=========="
echo "=========="
echo "===== Hard tuned ====="
echo "=========="
echo "=========="
echo "=========="
python3 -u ensemble_voting.py --mode hard --use-tuned --debug --save-preds ../approaches/moral-values/output/moral-values-tuned-hard-champion-val.tsv | tee ensemble_results/presence/moral-values-tuned-hard.txt
echo "=========="
echo "=========="
echo "=========="
echo "===== Soft tuned ====="
echo "=========="
echo "=========="
echo "=========="
python3 -u ensemble_voting.py --mode soft --threshold 0.3 --debug --save-preds ../approaches/moral-values/output/moral-values-tuned-soft-champion-val.tsv | tee ensemble_results/presence/moral-values-tuned-soft.txt
echo "=========="
echo "=========="
echo "=========="
echo "===== Weighted ====="
echo "=========="
echo "=========="
echo "=========="
python3 -u ensemble_voting.py --mode weighted --debug --save-preds ../approaches/moral-values/output/moral-values-fixed-weighted-champion-val.tsv | tee ensemble_results/presence/moral-values-fixed-weighted.txt
echo "=========="
echo "=========="
echo "=========="
echo "===== Weighted tuned ====="
echo "=========="
echo "=========="
echo "=========="
python3 -u ensemble_voting.py --mode weighted --use-tuned --debug --save-preds ../approaches/moral-values/output/moral-values-tuned-weighted-champion-val.tsv | tee ensemble_results/presence/moral-values-tuned-weighted.txt
# echo "=========="
# echo "=========="
# echo "=========="
# echo "===== Hard per label ====="
# echo "=========="
# echo "=========="
# echo "=========="
# python3 ensemble_per_label.py --mode hard --debug | tee ensemble_results/moral-values/per_label-hard.txt
# echo "=========="
# echo "=========="
# echo "=========="
# echo "===== Soft per label ====="
# echo "=========="
# echo "=========="
# echo "=========="
# python3 ensemble_per_label.py --mode soft --debug | tee ensemble_results/moral-values/per_label-soft.txt