#!/usr/bin/env bash

# Change route to results and the model list in Python files to save all ensemble results

echo "=========="
echo "=========="
echo "=========="
echo "===== Hard ====="
echo "=========="
echo "=========="
echo "=========="
python3 -u ensemble_voting.py --mode hard --debug --save-preds ../approaches/ensembles/self-trans/output/fixed-hard-champion-test.tsv --test --subset "Humility,Benevolence: caring,Benevolence: dependability,Universalism: concern,Universalism: nature,Universalism: tolerance" | tee ensemble_results/final/self-trans/test-fixed-hard.txt
echo "=========="
echo "=========="
echo "=========="
echo "===== Soft ====="
echo "=========="
echo "=========="
echo "=========="
python3 -u ensemble_voting.py --mode soft --debug --save-preds ../approaches/ensembles/self-trans/output/fixed-soft-champion-test.tsv --test --subset "Humility,Benevolence: caring,Benevolence: dependability,Universalism: concern,Universalism: nature,Universalism: tolerance" | tee ensemble_results/final/self-trans/test-fixed-soft.txt
echo "=========="
echo "=========="
echo "=========="
echo "===== Hard tuned ====="
echo "=========="
echo "=========="
echo "=========="
python3 -u ensemble_voting.py --mode hard --use-tuned --debug --save-preds ../approaches/ensembles/self-trans/output/tuned-hard-champion-test.tsv --test --subset "Humility,Benevolence: caring,Benevolence: dependability,Universalism: concern,Universalism: nature,Universalism: tolerance" | tee ensemble_results/final/self-trans/test-tuned-hard.txt
echo "=========="
echo "=========="
echo "=========="
echo "===== Soft tuned ====="
echo "=========="
echo "=========="
echo "=========="
python3 -u ensemble_voting.py --mode soft --threshold 0.29 --debug --save-preds ../approaches/ensembles/self-trans/output/tuned-soft-champion-test.tsv --test --subset "Humility,Benevolence: caring,Benevolence: dependability,Universalism: concern,Universalism: nature,Universalism: tolerance" | tee ensemble_results/final/self-trans/test-tuned-soft.txt
echo "=========="
echo "=========="
echo "=========="
echo "===== Weighted ====="
echo "=========="
echo "=========="
echo "=========="
python3 -u ensemble_voting.py --mode weighted --debug --save-preds ../approaches/ensembles/self-trans/output/fixed-weighted-champion-test.tsv --test --subset "Humility,Benevolence: caring,Benevolence: dependability,Universalism: concern,Universalism: nature,Universalism: tolerance" | tee ensemble_results/final/self-trans/test-fixed-weighted.txt
echo "=========="
echo "=========="
echo "=========="
echo "===== Weighted tuned ====="
echo "=========="
echo "=========="
echo "=========="
python3 -u ensemble_voting.py --mode weighted --use-tuned --debug --save-preds ../approaches/ensembles/self-trans/output/tuned-weighted-champion-test.tsv --test --subset "Humility,Benevolence: caring,Benevolence: dependability,Universalism: concern,Universalism: nature,Universalism: tolerance" | tee ensemble_results/final/self-trans/test-tuned-weighted.txt
# echo "=========="
# echo "=========="
# echo "=========="
# echo "===== Hard per label ====="
# echo "=========="
# echo "=========="
# echo "=========="
# python3 ensemble_per_label.py --mode hard --debug | tee ensemble_results/final/self-trans/per_label-hard.txt
# echo "=========="
# echo "=========="
# echo "=========="
# echo "===== Soft per label ====="
# echo "=========="
# echo "=========="
# echo "=========="
# python3 ensemble_per_label.py --mode soft --debug | tee ensemble_results/final/self-trans/per_label-soft.txt